### ISSUE TITLE
Micronaut 4 Support

### ISSUE THREAD

**Issue by saw303** [camunda-community-hub/micronaut-camunda-external-client#151]
Recently Micronaut 4 was released. Unfortunately, Micronaut 4 isn't binary compatible with Micronaut 3 and in order to make it work, it requires a new [micronaut-camunda-external-client](https://github.com/camunda-community-hub/micronaut-camunda-external-client)` compiled with Micronaut 4.

**Comment by tobiasschaefer** [comment]
Hi @saw303 ,

happy to hear that you're still using it 👍 

I've actually already tried migrating to 4.0 following the instructions on https://micronaut.io/2023/05/09/upgrade-to-micronaut-framework-4-0-0/ and https://micronaut.io/2023/07/14/upgrade-to-micronaut-framework-4-with-openrewrite-and-gradle/ but I was not yet successful.

I just pushed my local branch and created a PR but its failing: #152 . I haven't had the time to look closer. Feel free to contribute :-)

**Comment by saw303** [comment]
@tobiasschaefer check my PR. IMHO this should work

**Comment by tobiasschaefer** [comment]
@saw303 : your PR is merged (thanks for that!) and I created release 3.0.0 which is built with Micronaut 4.

Please try it out and looking forward to a short feedback.

**Comment by saw303** [comment]
@tobiasschaefer will do. I get back to you tomorrow afternoon. Thanks for merging 👍🏻

**Comment by saw303** [comment]
There are some issues on Micronaut 4. *(This comment is work in progress, as I'm going to collect all my findings here)**

**JAXB**

Camunda 7 still requires `JAXB` from the old `javax` package name.

```
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [info.novatec.micronaut.camunda.external.client.feature.ExternalWorkerSubscriptionCreator]

Message: javax/xml/bind/JAXBException
```

Maybe this one is missing?

```groovy
runtimeOnly "javax.xml.bind:jaxb-api:2.3.1"
```

**Comment by tobiasschaefer** [comment]
Hi @saw303 ,

I cannot reproduce your issue.

If I start the client at https://github.com/camunda-community-hub/micronaut-camunda-external-client/tree/main/micronaut-camunda-external-client-example running against a server on Micronaut 3 (Micronaut 4 is not yet supported for https://github.com/camunda-community-hub/micronaut-camunda-platform-7) it starts without any issues and processes the external tasks.

I see that we currently have
`api("com.sun.xml.bind:jaxb-impl:$jaxbImpl")` defined in https://github.com/camunda-community-hub/micronaut-camunda-external-client/blob/main/micronaut-camunda-external-client-feature/build.gradle#L27
whereas this is version 2.3.6 with 2.3.8 (February 2023) also working (strange that dependabot didn't create a PR...). Newer versions (3.x or 4.x) don't work.

Alternatively, this could be
`api "javax.xml.bind:jaxb-api:2.3.1"` (October 2018) (similar to your suggestion)

From the package name your suggestion looks better but the `com.sun.xml.bind` dependency is much newer.

I'm unsure if we should use `com.sun.xml.bind:jaxb-impl:2.3.8` or `javax.xml.bind:jaxb-api:2.3.1`. Do you have a clear opinion?
